// Code generated by go generate; DO NOT EDIT.
package config

const (
	ServerURL = "wss://localhost:8443"
	ServerUsername = "agent001"
	ServerPassword = "password"
)

const (
	ServiceName = "agent001"
	ServiceWorkerName = "agent001"
	ServiceVersion = "1.0.0"
)
