// Code generated by go generate; DO NOT EDIT.
package config

const (
	ServerURL = "wss://localhost:8443"
	ServerUsername = "agent001"
	ServerPassword = "password"
)

const (
	ServiceName = "vessel"
	ServiceWorkerName = "vessel-worker"
	ServiceVersion = "1.0.0"
	ServiceSubjectsRpc = "rpc"
	ServiceSubjectsData = "data"
	ServiceSubjectsStdin = "stdin"
	ServiceSubjectsStdout = "stdout"
)
