// Code generated by go generate; DO NOT EDIT.
package config

var (
	Servers = []string{}
	UserJWT = ""
	UserKeySeed = ""
	ServiceName = ""
	ServiceVersion = ""
	Modules = func() map[string]any {
		return nil
	}
	Builtins = func() map[string]any {
		return nil
	}
)
